version: "3"

volumes:
  postgres:
    driver: local
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
  web:
    build: .
    tty: true
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
